# Generated by Django 4.1.2 on 2022-10-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('testimonial_title', models.CharField(max_length=150, verbose_name='Post Title')),
                ('testimonial_name', models.CharField(max_length=150, verbose_name='Testimonial Name')),
                ('testimonial_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Testimonial Image')),
                ('testimonial_contents', models.TextField()),
            ],
        ),
    ]
