# Generated by Django 4.1.2 on 2022-10-15 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_testimonial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_title',
            field=models.CharField(max_length=150, verbose_name='Testimonial Title'),
        ),
    ]
