# Generated by Django 4.1.2 on 2022-10-15 15:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app1', '0004_jobcategories_testimonial_testimonial_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=150, verbose_name='Category name')),
                ('category_description', models.TextField(verbose_name='Description')),
            ],
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='testimonial_contents',
            field=models.TextField(verbose_name='Testimonial Contents'),
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=150, verbose_name='Post Title')),
                ('post_img', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Post Featured Image')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('post_contents', models.TextField(verbose_name='Post Contents')),
                ('post_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('post_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.postcategory', verbose_name='Post Category')),
            ],
        ),
    ]
