# Generated by Django 4.1.2 on 2022-10-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_postcategory_alter_testimonial_testimonial_contents_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postcategory',
            name='category_description',
            field=models.TextField(blank=True, null=True, verbose_name='Description'),
        ),
    ]
