# Generated by Django 4.1.2 on 2022-10-16 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_alter_postcategory_category_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_title', models.CharField(max_length=150, verbose_name='Service Title')),
                ('service_img', models.ImageField(upload_to='', verbose_name='Post Service Image')),
                ('service_contents', models.TextField(verbose_name='Service Contents')),
            ],
        ),
    ]
