# Generated by Django 4.1.2 on 2022-10-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_addservice'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=150, verbose_name='Site Name')),
                ('site_logo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Site Logo')),
                ('site_address', models.TextField(blank=True, null=True, verbose_name='Company Address')),
                ('site_phone', models.CharField(blank=True, max_length=150, null=True, verbose_name='Company Phone Number')),
                ('site_email1', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Company Email')),
                ('site_email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Customer Service Email')),
            ],
        ),
    ]
