# Generated by Django 4.1.2 on 2022-10-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_sitesetting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(max_length=150, verbose_name='Name')),
                ('contact_email', models.EmailField(max_length=150, verbose_name='Email Address')),
                ('contact_subject', models.CharField(max_length=150, verbose_name='Subject')),
                ('contact_contents', models.TextField(verbose_name='Contact Message')),
            ],
        ),
    ]
