# Generated by Django 4.1.2 on 2022-10-28 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0010_alter_blogpost_options_blogpost_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Draft'), (1, 'Publish')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='updated_on',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
