# Generated by Django 4.1.2 on 2022-11-11 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0014_commentlike_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
